######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 17:12:32 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += karenina.h
SOURCES += karenina.cpp main.cpp
