######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 12 12:31:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
