######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 15:02:20 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += absolute.cpp
