######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 19 15:55:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += cursors.cpp
