######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 22 00:58:51 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timer.h
SOURCES += main.cpp timer.cpp
