######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 16:58:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
