######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 23 19:35:35 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gradients.h lines.h puff.h shapes.h
SOURCES += gradients.cpp lines.cpp main.cpp puff.cpp shapes.cpp
