######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 19 13:52:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first.cpp
