######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 20 20:50:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += simplemenu.h
SOURCES += main.cpp simplemenu.cpp
