######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 20 23:56:26 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += anothermenu.h
SOURCES += anothermenu.cpp main.cpp
