######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 23 23:20:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += burning.h widget.h
SOURCES += burning.cpp main.cpp widget.cpp
