######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 23 18:57:32 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += splitter.h
SOURCES += main.cpp splitter.cpp
