######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 22 13:29:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += statusbar.h
SOURCES += main.cpp statusbar.cpp
