######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 17:35:26 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += click.h
SOURCES += lines.cpp main.cpp
