######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 17:44:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keypress.h
SOURCES += keypress.cpp main.cpp
