######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 15:11:11 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += verticalbox.h
SOURCES += main.cpp verticalbox.cpp
