######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 16:33:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buttons.h
SOURCES += buttons.cpp main.cpp
