######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 16:45:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += layouts.h
SOURCES += border.cpp main.cpp
