######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 19 18:34:50 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += communicate.h
SOURCES += communicate.cpp main.cpp
