######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 17:53:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += move.h
SOURCES += main.cpp move.cpp
