######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 19 13:34:27 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += dir.cpp
