######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 21 17:57:25 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += disconnect.h
SOURCES += disconnect.cpp main.cpp
