######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 19 13:22:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += file.cpp
